services:
  imagex:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/imagex"]
    ports:
      - "5001:8080"  # Adjust the port if needed
    volumes:
      - ./data:/app  # Mounts local directory for live changes (optional)
    environment:
      - CGO_ENABLED=1
      - GOOS=linux
